import io
import json
import os
import re

import pandas as pd
from pypdf import PdfReader
from docx import Document
from docx.shared import Pt
from fpdf import FPDF

from mcqgenrator.logger import logger

# Bundled Unicode font (DejaVu Sans) so PDF export doesn't crash on
# non-Latin-1 characters -- math symbols (Δ, π...), Greek, Cyrillic, and
# accented Latin all work. DejaVu doesn't cover Arabic/Devanagari/CJK; for
# those languages Word/CSV/JSON export (which are fully Unicode-safe)
# should be used instead -- see the fallback in _line() below.
_FONTS_DIR = os.path.normpath(
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "fonts")
)
_UNICODE_FONT_FAMILY = "DejaVu"
_UNICODE_FONT_FILES = {
    "": os.path.join(_FONTS_DIR, "DejaVuSans.ttf"),
    "B": os.path.join(_FONTS_DIR, "DejaVuSans-Bold.ttf"),
    "I": os.path.join(_FONTS_DIR, "DejaVuSans-Oblique.ttf"),
}


def read_file(file):
    """Extract raw text from an uploaded .pdf or .txt file."""
    name = getattr(file, "name", "")

    if name.lower().endswith(".pdf"):
        try:
            reader = PdfReader(file)
            text = ""
            for page in reader.pages:
                extracted = page.extract_text() or ""
                text += extracted
            if not text.strip():
                raise ValueError(
                    "No extractable text found (the PDF may be scanned/image-based)."
                )
            return text
        except Exception as e:
            logger.exception("Failed to read PDF")
            raise Exception(f"Error reading the PDF file: {e}")

    elif name.lower().endswith(".txt"):
        try:
            return file.read().decode("utf-8")
        except Exception as e:
            logger.exception("Failed to read TXT")
            raise Exception(f"Error reading the text file: {e}")

    else:
        raise Exception("Unsupported file format. Only PDF and TXT files are supported.")


def combine_texts(texts: list) -> str:
    """Join multiple source documents into one body of text with clear separators."""
    parts = []
    for i, t in enumerate(texts, start=1):
        if t and t.strip():
            parts.append(f"--- Source {i} ---\n{t.strip()}")
    return "\n\n".join(parts)


def _strip_code_fences(s: str) -> str:
    """LLMs sometimes wrap JSON in ```json ... ``` fences -- strip those off."""
    s = s.strip()
    s = re.sub(r"^```(?:json)?\s*", "", s)
    s = re.sub(r"\s*```$", "", s)
    return s.strip()


def _infer_type(value: dict) -> str:
    if "type" in value:
        return value["type"]
    # backward compatibility with the older (pre question-type) schema
    if "options" in value:
        return "mcq"
    if "statement" in value:
        return "true_false"
    return "short_answer"


def _question_text(value: dict) -> str:
    return value.get("question", value.get("mcq", value.get("statement", "")))


def get_table_data(quiz_str):
    """
    Parse the model's JSON quiz output into a list of dict rows suitable for
    a dataframe/table. Supports mcq / true_false / fill_blank / short_answer,
    including quizzes generated by the older schema.
    Returns False on failure (caller should check for that).
    """
    try:
        cleaned = _strip_code_fences(quiz_str)
        quiz_dict = json.loads(cleaned)
        rows = []

        for _, value in quiz_dict.items():
            qtype = _infer_type(value)
            question_text = _question_text(value)

            if qtype == "mcq" and "options" in value:
                choices = " || ".join(
                    f"{opt}-> {opt_val}" for opt, opt_val in value["options"].items()
                )
            elif qtype == "true_false":
                choices = "True || False"
            else:
                choices = "—"

            rows.append(
                {
                    "Type": qtype.replace("_", " ").title(),
                    "Question": question_text,
                    "Choices": choices,
                    "Correct": value.get("correct", ""),
                    "Bloom Level": value.get("bloom_level", ""),
                    "Explanation": value.get("explanation", ""),
                }
            )

        return rows

    except Exception:
        logger.exception("Failed to parse quiz JSON")
        return False


def quiz_dict_from_str(quiz_str):
    """Return the raw parsed quiz dict (used for interactive self-check UI)."""
    try:
        return json.loads(_strip_code_fences(quiz_str))
    except Exception:
        logger.exception("Failed to parse quiz dict")
        return None


def estimate_min_word_count(mcq_count: int) -> int:
    """A rough heuristic: need enough source text to support the requested
    number of questions without the model repeating/inventing content."""
    return max(80, mcq_count * 25)


# --------------------------------------------------------------------------- #
# Export helpers
# --------------------------------------------------------------------------- #

def export_to_csv_bytes(df: pd.DataFrame) -> bytes:
    return df.to_csv(index=False).encode("utf-8")


def export_to_docx_bytes(df: pd.DataFrame, review: str, subject: str, tone: str) -> bytes:
    doc = Document()
    doc.add_heading(f"{subject} Quiz", level=1)
    doc.add_paragraph(f"Difficulty / Tone: {tone}")
    doc.add_paragraph("")

    for i, row in df.iterrows():
        p = doc.add_paragraph()
        run = p.add_run(f"Q{i}. {row['Question']}")
        run.bold = True
        run.font.size = Pt(12)

        if row["Choices"] != "—":
            choices_p = doc.add_paragraph(str(row["Choices"]).replace(" || ", "\n"))
            choices_p.paragraph_format.left_indent = Pt(18)

        ans_p = doc.add_paragraph()
        ans_run = ans_p.add_run(f"Correct answer: {row['Correct']}")
        ans_run.italic = True

        if row.get("Explanation"):
            exp_p = doc.add_paragraph(f"Why: {row['Explanation']}")
            exp_p.paragraph_format.left_indent = Pt(18)

        doc.add_paragraph("")

    if review:
        doc.add_heading("Expert Review", level=2)
        doc.add_paragraph(review)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


class _QuizPDF(FPDF):
    def header(self):
        pass


def _register_pdf_font(pdf) -> str:
    """Register the bundled Unicode TTF font if the files are present;
    otherwise fall back to the built-in Helvetica (Latin-1 only, but
    always available so export never hard-fails)."""
    if all(os.path.isfile(p) for p in _UNICODE_FONT_FILES.values()):
        try:
            for style, path in _UNICODE_FONT_FILES.items():
                pdf.add_font(_UNICODE_FONT_FAMILY, style, path)
            return _UNICODE_FONT_FAMILY
        except Exception:
            logger.exception("Failed to register Unicode PDF font, falling back to Helvetica")
    else:
        logger.warning("Unicode PDF fonts not found under %s -- falling back to Helvetica.", _FONTS_DIR)
    return "Helvetica"


def _line(pdf, h, text):
    """multi_cell that always returns the cursor to the left margin / next
    line, and never lets an unsupported character crash the whole export.
    DejaVu Sans covers Latin (incl. accents), Greek, Cyrillic, and common
    math symbols; if a character still isn't supported (e.g. Arabic,
    Devanagari, CJK -- DejaVu doesn't include these), that one line
    degrades to an ASCII-safe version instead of raising."""
    pdf.set_x(pdf.l_margin)
    try:
        pdf.multi_cell(0, h, text)
    except Exception:
        logger.warning("PDF font couldn't render some characters in a line; using ASCII fallback for it.")
        safe_text = text.encode("ascii", "replace").decode("ascii")
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(0, h, safe_text)


def export_to_pdf_bytes(df: pd.DataFrame, review: str, subject: str, tone: str) -> bytes:
    pdf = _QuizPDF()
    font = _register_pdf_font(pdf)
    pdf.add_page()
    pdf.set_font(font, "B", 16)
    _line(pdf, 10, f"{subject} Quiz")
    pdf.set_font(font, "", 11)
    _line(pdf, 8, f"Difficulty / Tone: {tone}")
    pdf.ln(4)

    for i, row in df.iterrows():
        pdf.set_font(font, "B", 11)
        _line(pdf, 7, f"Q{i}. {row['Question']}")
        pdf.set_font(font, "", 10)
        if row["Choices"] != "—":
            for choice in str(row["Choices"]).split(" || "):
                _line(pdf, 6, f"   {choice}")
        pdf.set_font(font, "I", 10)
        _line(pdf, 6, f"   Correct: {row['Correct']}")
        if row.get("Explanation"):
            _line(pdf, 6, f"   Why: {row['Explanation']}")
        pdf.ln(2)

    if review:
        pdf.ln(4)
        pdf.set_font(font, "B", 13)
        _line(pdf, 8, "Expert Review")
        pdf.set_font(font, "", 10)
        _line(pdf, 6, review)

    return bytes(pdf.output())


def export_to_gift_bytes(quiz_dict: dict, subject: str) -> bytes:
    """Moodle GIFT format -- importable by Moodle and several other LMSes."""
    def esc(s):
        return str(s).replace("{", "(").replace("}", ")").replace("~", "-").replace("=", "-")

    lines = [f"// {subject} quiz exported from AnswerKey Studio", ""]
    for i, (_, q) in enumerate(quiz_dict.items(), start=1):
        qtype = _infer_type(q)
        question = esc(_question_text(q))

        if qtype == "mcq" and "options" in q:
            correct_letter = str(q.get("correct", "")).strip().lower()
            opt_lines = []
            for letter, text in q["options"].items():
                prefix = "=" if letter.strip().lower() == correct_letter else "~"
                opt_lines.append(f"{prefix}{esc(text)}")
            lines.append(f"::Q{i}:: {question} {{")
            lines.extend(opt_lines)
            lines.append("}")
        elif qtype == "true_false":
            correct = str(q.get("correct", "")).strip().lower()
            tf = "TRUE" if correct.startswith("t") else "FALSE"
            lines.append(f"::Q{i}:: {question} {{{tf}}}")
        elif qtype == "fill_blank":
            answer = esc(q.get("correct", ""))
            if "____" in question:
                lines.append(f"::Q{i}:: {question.replace('____', '{=' + answer + '}')}")
            else:
                lines.append(f"::Q{i}:: {question} {{={answer}}}")
        else:  # short_answer
            answer = esc(q.get("correct", ""))
            lines.append(f"::Q{i}:: {question} {{={answer}}}")

        lines.append("")

    return "\n".join(lines).encode("utf-8")


def export_to_quizlet_tsv_bytes(quiz_dict: dict) -> bytes:
    """Tab-separated term/definition pairs -- pastes directly into Quizlet's
    'Import' flow (Term / Definition, row per line)."""
    rows = []
    for _, q in quiz_dict.items():
        qtype = _infer_type(q)
        question = _question_text(q)

        if qtype == "mcq" and "options" in q:
            opts = "; ".join(f"{k}) {v}" for k, v in q["options"].items())
            term = f"{question} [{opts}]"
        else:
            term = question

        definition = str(q.get("correct", ""))
        term = term.replace("\t", " ").replace("\n", " ")
        definition = definition.replace("\t", " ").replace("\n", " ")
        rows.append(f"{term}\t{definition}")

    return "\n".join(rows).encode("utf-8")